version: '3.8'

services:
  app:
    build: .
    container_name: backend_app
    environment:
      - DB_DSN=host=db port=5432 user=myuser password=mypassword dbname=mydatabase sslmode=disable
      - LISTEN_ADDR=8080
      - DB_SCHEMA_NAME=alan_tabeo_test_task
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
